
#'Variant16x: Biomes You Go' Common Configuration File | Game Version: 1.16.5
[variant16x_biomesyougo]

	#General Settings
	#NOTE: Changing 'General Settings' WILL OVERRIDE Custom Settings!
	[variant16x_biomesyougo.general]
		#Enables/Disables ALL Pressure Plate Variants
		enablePressurePlates = true
		#Enables/Disables ALL Button Variants
		enableButtons = true
		#Enables/Disables ALL Stairs Variants
		enableStairs = true
		#Enables/Disables ALL Wall Variants
		enableWalls = true
		#Enables/Disables ALL Fence Gate Variants
		enableFenceGates = true
		#Enables/Disables ALL Fence Variants
		enableFences = true
		#Enables/Disables ALL Slab Variants
		enableSlabs = true

	#Custom Wall Settings
	[variant16x_biomesyougo.walls]
		#Enables/Disables Mud Brick Wall
		enableBrickWalls = true
		#Enables/Disables Sandstone Wall Variants
		enableSandstoneWalls = true
		#Enables/Disables Nether Brick Wall Variants
		enableNetherBrickWalls = true
		#Enables/Disables Raw Quartz Wall
		enableQuartzWalls = true

	#Custom Fence Settings
	[variant16x_biomesyougo.fences]
		#Enables/Disables Wood/Hyphae Fence Variants
		enableWoodFences = true
		#Enables/Disables Nether Brick Fence Variants
		enableNetherBrickFences = true

	#Custom Button Settings
	[variant16x_biomesyougo.buttons]
		#Enables/Disables Sandstone Button Variants
		enableSandstoneButtons = true
		#Enables/Disables Stone Button Variants
		enableStoneButtons = true
		#Enables/Disables Wood/Hyphae Button Variants
		enableWoodButtons = true
		#Enables/Disables Mud Brick Button
		enableBrickButtons = true
		#Enables/Disables Raw Quartz Button
		enableQuartzButtons = true
		#Enables/Disables Nether Brick Button Variants
		enableNetherBrickButtons = true
		#Enables/Disables End Stone Button Variants
		enableEndStoneButtons = true
		#Enables/Disables Purpur Stone Button
		enablePurpurButtons = true

	#Custom Pressure Plate Settings
	[variant16x_biomesyougo.pressurePlates]
		#Enables/Disables Wood/Hyphae Pressure Plate Variants
		enableWoodPressurePlates = true
		#Enables/Disables Mud Brick Pressure Plate
		enableBrickPressurePlates = true
		#Enables/Disables Nether Brick Pressure Plate Variants
		enableNetherBrickPressurePlates = true
		#Enables/Disables Sandstone Pressure Plate Variants
		enableSandstonePressurePlates = true
		#Enables/Disables Stone Pressure Plate Variants
		enableStonePressurePlates = true
		#Enables/Disables Purpur Stone Pressure Plate
		enablePurpurPressurePlates = true
		#Enables/Disables End Stone Pressure Plate Variants
		enableEndStonePressurePlates = true
		#Enables/Disables Raw Quartz Pressure Plate
		enableQuartzPressurePlates = true

	#Custom Stairs Settings
	[variant16x_biomesyougo.stairs]
		#Enables/Disables Wood/Hyphae Stairs Variants
		enableWoodStairs = true
		#Enables/Disables Raw Quartz Stairs
		enableQuartzStairs = true
		#Enables/Disables Mud Brick Stairs
		enableBrickStairs = true
		#Enables/Disables Nether Brick Stairs Variants
		enableNetherBrickStairs = true
		#Enables/Disables Sandstone Stairs Variants
		enableSandstoneStairs = true

	#Custom Fence Gate Settings
	[variant16x_biomesyougo.fenceGates]
		#Enables/Disables Wood/Hyphae Fence Gate Variants
		enableWoodFenceGates = true

	#Custom Slab Settings
	[variant16x_biomesyougo.slabs]
		#Enables/Disables Mud Brick Slab
		enableBrickSlabs = true
		#Enables/Disables Wood/Hyphae Slab Variants
		enableWoodSlabs = true
		#Enables/Disables Sandstone Slab Variants
		enableSandstoneSlabs = true
		#Enables/Disables Nether Brick Slab Variants
		enableNetherBrickSlabs = true
		#Enables/Disables Raw Quartz Slab
		enableQuartzSlabs = true

