
[advancedcompass]
	#Angle threshold for rendering icons (from 15 to 180)
	#Range: 15 ~ 180
	angleThreshold = 90
	#Vertical offset from top edge of the screen (from 0 to 50)
	#Range: 0 ~ 50
	yOffset = 4
	#Show players
	showPlayers = true
	#Auto icon generation type
	#Allowed Values: HEAD_FIRST, FULL_BODY, OFF
	generationType = "HEAD_FIRST"
	#Maximum distance to entity for rendering (from 0 to 999)
	#Range: 0 ~ 999
	maxDistance = 50
	#Maximum radius to merge entity into groups (from 5 to 15)
	#Range: 5 ~ 15
	groupRadius = 10
	#Compass show mode
	#Allowed Values: OFF, ALWAYS_ON, MAIN_HAND, BOTH_HANDS, ANY_SLOT
	showMode = "OFF"
	#Compass height
	#Range: 8 ~ 50
	compassHeight = 22
	#Merge entities into groups
	groupEntities = true
	#Overlap threshold
	#Range: 0 ~ 10
	overlapThreshold = 4
	#Hide overlapped icons
	hideOverlapped = true
	#Coordinates font scale
	#Range: 50 ~ 200
	coordinatesScale = 100
	#Angle of view that fits into the compass (from 30 to 360)
	#Range: 30 ~ 360
	viewAngle = 70
	#Show coordinates
	#Allowed Values: OFF, ABOVE, BELOW
	coordinatesMode = "OFF"
	#Show distance
	showDistance = true
	#Move vanilla bossbar below the compass
	moveBossbar = true
	#Compass width
	#Range: 100 ~ 9999
	compassWidth = 412
	#Create waypoint on death
	autoDeathWaypoint = true
	#Icon scale
	#Range: 50 ~ 200
	iconScale = 100

