
#Dungeons Mod Configuration Settings
[general]
	#Should players leave a ghost when they die? 0 to disable, 1 to always, 100/positiveValues chance
	#Range: > 0
	"Ghost Players" = 20

[bosses]

	[bosses.kraken]
		"Kraken Loot Table" = "dungeonsmod:entities/kraken"

	[bosses.crawler]
		"Crawler Loot Table" = "dungeonsmod:entities/crawler"

	[bosses.king]
		"King Loot Table" = "dungeonsmod:entities/king"

	[bosses.ironslime]
		"Ironslime Loot Table" = "dungeonsmod:entities/ironslime"

	[bosses.deserted]
		"Deserted Loot Table" = "dungeonsmod:entities/deserted"

	[bosses.voidmaster]
		"Voidmaster Loot Table" = "dungeonsmod:entities/voidmaster"

	[bosses.sun]
		"Sun Loot Table" = "dungeonsmod:entities/sun"

[difficulty]
	#[BETA] For manual adjustment. Recommended number = (Highest Weapon Damage / 20) . For reference, Vanilla defaults equivalent : Easy = 0.25, Normal = 0.5, Hard = 0.75. Values > 1 requires Attribute Fix Mod. For using server difficulty = 0
	#Range: -0.25 ~ 1000.0
	"Custom Difficulty Value" = 0.0
	#[BETA] This will make bosses to scale with the number of players near and the world difficulty 
	"Multiplayer Scaling" = true

[invocations]
	#Enable Traveler invocation
	"Traveler Invocation" = true
	#Enable Lord Skeleton invocation
	"Lord Skeleton Invocation" = true
	#Enable Winter Hunter invocation
	"Winter Hunter Invocation" = true
	#Enable Sun invocation
	"Sun Invocation" = true

[items]

	[items.times]
		#Home Gem Cast Time in Ticks
		#Range: > 0
		"Home Gem Cast Time" = 200
		#Sun Overdrive Cast Time in Ticks
		#Range: > 0
		"Sun Overdrive Cast Time" = 200
		#Sun Overdrive Cooldown in Ticks
		#Range: > 0
		"Sun Overdrive Cooldown" = 144000
		#Home Gem Cooldown in Ticks
		#Range: > 0
		"Home Gem Cooldown" = 18000

	[items.activations]

		[items.activations.back_pergamine]
			Enable = true

		[items.activations.unstable_map]
			Enable = true

		[items.activations.home_gem]
			Enable = true

		[items.activations.golden_bone]
			Enable = true

		[items.activations.sun_overdrive]
			Enable = true

[mobs]

	[mobs.rogue]
		"Rogue Loot Table" = "dungeonsmod:entities/rogue"
		#Range: > 0
		"Rogue Weight" = 1

	[mobs.deadhound]
		"Deadhound Loot Table" = "dungeonsmod:entities/deadhound"

	[mobs.anthermite]
		"Anthermite Loot Table" = "dungeonsmod:entities/anthermite"
		#Range: > 0
		"Anthermite Weight" = 2

	#Blacklisted biomes in which no mobs will spawn
	[mobs.blacklisted-biomes]
		"Blacklisted Biomes" = ["minecraft:modified_jungle_edge"]

	[mobs.piranha]
		#Range: > 0
		"Piranha Weight" = 2
		"Piranha Loot Table" = "dungeonsmod:entities/piranha"

	[mobs.lordskeleton]
		"Lordskeleton Loot Table" = "dungeonsmod:entities/lordskeleton"

	[mobs.scientist]
		#Range: 0 ~ 100
		"Scientist Weight(Percentage)" = 100
		"Scientist Loot Table" = "dungeonsmod:entities/scientist"

	[mobs.guard]
		"Guard Loot Table" = "dungeonsmod:entities/guard"
		#Range: 0 ~ 100
		"Guard Weight(Percentage)" = 100

	[mobs.slimewolf]
		"Slimewolf Loot Table" = "dungeonsmod:entities/slimewolf"
		#Range: 0 ~ 100
		"Slimewolf Weight(Percentage)" = 100

	[mobs.winterhunter]
		"Winterhunter Loot Table" = "dungeonsmod:entities/winterhunter"

	[mobs.pice]
		"Pice Loot Table" = "dungeonsmod:entities/pice"
		#Range: > 0
		"Pice Weight" = 3

	[mobs.whirlwind]
		#Range: > 0
		"Whirlwind Weight" = 1

	[mobs.notehead]
		#Range: > 0
		"Notehead Weight" = 1
		"Notehead Loot Table" = "dungeonsmod:entities/notehead"

	[mobs.crow]
		#Range: > 0
		"Crow Weight" = 4
		"Crow Loot Table" = "dungeonsmod:entities/crow"

	[mobs.mimic]
		"Mimic Loot Table" = "dungeonsmod:entities/mimic"
		#Range: > 0
		"Mimic Weight" = 5

	[mobs.slimond]
		"Slimond Loot Table" = "dungeonsmod:entities/slimond"
		#Range: > 0
		"Slimond Weight" = 1

	[mobs.pitcher]
		"Pitcher Loot Table" = "dungeonsmod:entities/pitcher"

	[mobs.haunter]
		"Haunter Loot Table" = "dungeonsmod:entities/haunter"
		#Range: > 0
		"Haunter Weight" = 100

[structures]

	[structures.the_pitcher]
		#Range: > 0
		"Seed Modifier" = 32127
		#Range: > 0
		Separation = 2
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 8

	#Blacklisted biomes in which no structures will spawn
	[structures.blacklisted-biomes]
		"Blacklisted Biomes" = ["minecraft:modified_jungle_edge"]

	[structures.the_origin]
		#Range: > 0
		"Seed Modifier" = 621556
		#Range: > 0
		Separation = 20
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 80

	[structures.the_house]
		#Range: > 0
		"Seed Modifier" = 9326560
		#Range: > 0
		Separation = 20
		#Range: 0 ~ 64
		Price = 2
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 80

	[structures.the_sewers]
		#Range: > 0
		"Seed Modifier" = 14341
		#Range: > 0
		Separation = 8
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 32

	[structures.the_ship]
		#Range: > 0
		"Seed Modifier" = 214556
		#Range: > 0
		Separation = 20
		#Range: 0 ~ 64
		Price = 8
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 80

	[structures.the_castle]
		#Range: > 0
		"Seed Modifier" = 5284629
		#Range: > 0
		Separation = 20
		#Range: 0 ~ 64
		Price = 15
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 80

	[structures.the_iron_mines]
		#Range: > 0
		"Seed Modifier" = 9326560
		#Range: > 0
		Separation = 20
		#Range: 0 ~ 64
		Price = 4
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 80

	[structures.the_catacombs]
		#Range: > 0
		"Seed Modifier" = 3252381
		#Range: > 0
		Separation = 20
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 80

	[structures.the_lab]
		#Range: > 0
		"Seed Modifier" = 3241280
		#Range: > 0
		Separation = 20
		#Range: 0 ~ 64
		Price = 20
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 80

	[structures.the_chapel]
		#Range: > 0
		"Seed Modifier" = 31632
		#Range: > 0
		Separation = 8
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 32

	[structures.the_camp]
		#Range: > 0
		"Seed Modifier" = 14357617
		#Range: > 0
		Separation = 8
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 32

	[structures.the_nest]
		#Range: > 0
		"Seed Modifier" = 58625
		#Range: > 0
		Separation = 4
		#1 to always, 100/positiveValues chance
		#Range: > 0
		"Spawing Chance" = 1
		#Range: > 0
		Spacing = 16

[traveler]
	#Traveler does not spawn in this radius if theres another traveler near
	#Range: 0 ~ 256
	"The One radius" = 64

