#allow horses to swim
doHorsesSwim = true

#Whitelist
[whitelist]
	#list of resourcelocations in string form
	whitelist = [""]

#Blacklist
[blacklist]
	#list of resourcelocations in string form
	blacklist = [""]

