
#gem set tools leveling config
["tool leveling"]
	#sets whether gem set tools gain perks from levels
	isToolLevelingEnabled = true

	["tool leveling"."leveling config"]
		axeKillsPerLevel = 100
		axeLogsPerLevel = 100
		hoeCropsPerLevel = 200
		pickaxeBlocksPerLevel = 200
		pickaxeOresPerLevel = 100
		swordKillsPerLevel = 100
		hoeHoesPerLevel = 500
		shovelBlocksPerLevel = 500
		axeBlocksPerLevel = 200

#whether mod loot spawns in chests
["loot spawning"]
	isLootSpawnEnabled = true

#whether minor gems spawn in unique biomes
["gem unique biome generation"]
	#sets whether minor gems spawn uniquely in specific biomes.Disable to make enabled gems generate in every overworld biome
	isUniqueBiomeGenerationEnabled = true

#overworld world generation config
["overworld generation"]
	opal_OreGenEnabled = true
	tanzanite_OreGenEnabled = true
	sapphire_OreGenEnabled = true
	citrine_OreGenEnabled = true
	ametrine_OreGenEnabled = true
	silver_OreGenEnabled = false
	morganite_OreGenEnabled = true
	kunzite_OreGenEnabled = true
	garnet_OreGenEnabled = true
	peridot_OreGenEnabled = true
	tourmaline_OreGenEnabled = true
	blackOpal_OreGenEnabled = true
	ruby_OreGenEnabled = true
	aquamarine_OreGenEnabled = true
	amethyst_OreGenEnabled = true
	topaz_OreGenEnabled = true
	spinel_OreGenEnabled = true
	iolite_OreGenEnabled = true
	zircon_OreGenEnabled = true
	#sets whether mod emerald ore generation is enabled
	emerald_OreGenEnabled = true
	alexandrite_OreGenEnabled = true

["nether generation"]
	kunzite_NetherOreGenEnabled = true
	zircon_NetherOreGenEnabled = true
	tanzanite_NetherOreGenEnabled = true
	citrine_NetherOreGenEnabled = true
	morganite_NetherOreGenEnabled = true
	spinel_NetherOreGenEnabled = true
	sapphire_NetherOreGenEnabled = true
	ruby_NetherOreGenEnabled = true
	diamond_NetherOreGenEnabled = true
	peridot_NetherOreGenEnabled = true
	garnet_NetherOreGenEnabled = true
	#sets whether vanilla emerald ore nether generation is enabled
	v_emerald_NetherOreGenEnabled = true
	ametrine_NetherOreGenEnabled = true
	tourmaline_NetherOreGenEnabled = true
	iolite_NetherOreGenEnabled = true
	amethyst_NetherOreGenEnabled = true
	aquamarine_NetherOreGenEnabled = true
	#sets whether mod emerald ore nether generation is enabled
	emerald_NetherOreGenEnabled = true
	topaz_NetherOreGenEnabled = true
	alexandrite_NetherOreGenEnabled = true
	blackOpal_NetherOreGenEnabled = true
	opal_NetherOreGenEnabled = true

