
[general]
	#This allows you hide or show the overlay in the top right of the screen when XRay is enabled
	showOverlay = true
	#This allows you to set your own outline thickness, I find that 1.0 is perfect but others my
	#think differently. The max is 5.0
	#Range: 1.0 ~ 5.0
	outlineThickness = 1.0

#DO NOT TOUCH!
[store]
	#DO NOT TOUCH!
	#This setting is for memory only and if changed to a value not supported
	#the game will crash on start up. This value can be changed in game very simply.
	#If you must change it then these are the valid values 0 -> 7
	#but please leave it alone :P
	#Range: 0 ~ 9
	radius = 3
	#Memory value for if you're currently wanting Lava to be rendered into the mix
	lavaActive = false

